---
name: "Hassfest"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
  push:
    branches:
      - "main"
      - "beta"
  pull_request:
    branches:
      - "main"
      - "beta"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hassfest:
    name: "Hassfest Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v7"

      - name: "Run hassfest validation"
        uses: "home-assistant/actions/hassfest@master"
