name: Lint

on:
  push:
    branches:
      - "main"
      - "beta"
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_lint.txt

      - name: Show resolved versions
        run: ruff --version

      - name: Run ruff
        run: ruff check --output-format=github .
